// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PortalCommunicationsAPI.Data;

#nullable disable

namespace PortalCommunicationsAPI.Migrations
{
    [DbContext(typeof(PortalCommunicationsDbContext))]
    [Migration("20241106190113_initcommit")]
    partial class initcommit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("PortalCommunicationsAPI.Models.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Device");

                    b.HasDiscriminator<string>("DeviceType").HasValue("Device");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("PortalCommunicationsAPI.Models.DeviceLog", b =>
                {
                    b.Property<int>("deviceLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("deviceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("loggedMessage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("loggedTime")
                        .HasColumnType("TEXT");

                    b.HasKey("deviceLogId");

                    b.HasIndex("deviceId");

                    b.ToTable("DeviceLog");
                });

            modelBuilder.Entity("PortalCommunicationsAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "JohnDoe@hotmail.com",
                            Password = "password",
                            Username = "John Doe"
                        },
                        new
                        {
                            Id = 2,
                            Email = "JanDoe@hotmail.com",
                            Password = "password",
                            Username = "Jane Doe"
                        },
                        new
                        {
                            Id = 3,
                            Email = "JohnSmith@hotmail.com",
                            Password = "password",
                            Username = "John Smith"
                        });
                });

            modelBuilder.Entity("PortalCommunicationsAPI.Models.Dehumidifier", b =>
                {
                    b.HasBaseType("PortalCommunicationsAPI.Models.Device");

                    b.Property<double>("humidityLevel")
                        .HasColumnType("REAL");

                    b.Property<double>("waterLevel")
                        .HasColumnType("REAL");

                    b.HasDiscriminator().HasValue("Dehumidifier");
                });

            modelBuilder.Entity("PortalCommunicationsAPI.Models.SmartFridge", b =>
                {
                    b.HasBaseType("PortalCommunicationsAPI.Models.Device");

                    b.Property<double>("freezerTemp")
                        .HasColumnType("REAL");

                    b.Property<double>("fridgeTemp")
                        .HasColumnType("REAL");

                    b.Property<double>("humidityLevel")
                        .HasColumnType("REAL");

                    b.ToTable("Device", t =>
                        {
                            t.Property("humidityLevel")
                                .HasColumnName("SmartFridge_humidityLevel");
                        });

                    b.HasDiscriminator().HasValue("SmartFridge");
                });

            modelBuilder.Entity("PortalCommunicationsAPI.Models.SmartOven", b =>
                {
                    b.HasBaseType("PortalCommunicationsAPI.Models.Device");

                    b.Property<double>("currentTemp")
                        .HasColumnType("REAL");

                    b.Property<double>("targetTemp")
                        .HasColumnType("REAL");

                    b.HasDiscriminator().HasValue("SmartOven");
                });

            modelBuilder.Entity("PortalCommunicationsAPI.Models.SmartVacuum", b =>
                {
                    b.HasBaseType("PortalCommunicationsAPI.Models.Device");

                    b.Property<double>("batteryLife")
                        .HasColumnType("REAL");

                    b.Property<string>("location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("notification")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("SmartVacuum");
                });

            modelBuilder.Entity("PortalCommunicationsAPI.Models.Thermostat", b =>
                {
                    b.HasBaseType("PortalCommunicationsAPI.Models.Device");

                    b.Property<double>("currentTemp")
                        .HasColumnType("REAL");

                    b.Property<double>("targetTemp")
                        .HasColumnType("REAL");

                    b.ToTable("Device", t =>
                        {
                            t.Property("currentTemp")
                                .HasColumnName("Thermostat_currentTemp");

                            t.Property("targetTemp")
                                .HasColumnName("Thermostat_targetTemp");
                        });

                    b.HasDiscriminator().HasValue("Thermostat");
                });

            modelBuilder.Entity("PortalCommunicationsAPI.Models.DeviceLog", b =>
                {
                    b.HasOne("PortalCommunicationsAPI.Models.Device", null)
                        .WithMany("DeviceLogs")
                        .HasForeignKey("deviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PortalCommunicationsAPI.Models.Device", b =>
                {
                    b.Navigation("DeviceLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
