// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PortalCommunicationsAPI.Data;

#nullable disable

namespace PortalCommunicationsAPI.Migrations
{
    [DbContext(typeof(PortalCommunicationsDbContext))]
    [Migration("20241105143613_initcommit")]
    partial class initcommit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("PortalCommunicationsAPI.Models.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Devices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Alarm",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Soundbar",
                            Status = "Inactive"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Bedroom Light 1",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Bedroom Light 2",
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("PortalCommunicationsAPI.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Password = "admin",
                            Username = "admin"
                        },
                        new
                        {
                            UserId = 2,
                            Password = "user",
                            Username = "user"
                        },
                        new
                        {
                            UserId = 3,
                            Password = "user2",
                            Username = "user2"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
