// <auto-generated />
using System;
using Databases;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Databases.Migrations
{
    [DbContext(typeof(SmartHomeContext))]
    [Migration("20241123040300_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Databases.DeviceLogModel", b =>
                {
                    b.Property<int>("deviceLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("deviceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("loggedMessage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("loggedTime")
                        .HasColumnType("TEXT");

                    b.HasKey("deviceLogId");

                    b.ToTable("devicesLog");
                });

            modelBuilder.Entity("Databases.DeviceModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeviceActivitydeviceLogId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("State")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DeviceActivitydeviceLogId");

                    b.ToTable("devices");
                });

            modelBuilder.Entity("Databases.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("Databases.DeviceModel", b =>
                {
                    b.HasOne("Databases.DeviceLogModel", "DeviceActivity")
                        .WithMany()
                        .HasForeignKey("DeviceActivitydeviceLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeviceActivity");
                });
#pragma warning restore 612, 618
        }
    }
}
